# Generated by Django 4.2.7 on 2025-11-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live Stream',
                'verbose_name_plural': 'Live Streams',
                'db_table': 'live_streams',
                'ordering': ['-actual_start_time'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=30, unique=True)),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('subscriber_count', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Channel',
                'verbose_name_plural': 'YouTube Channels',
                'db_table': 'youtube_channels',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video_path', models.FileField(blank=True, null=True, upload_to='recordings/videos/')),
                ('audio_path', models.FileField(blank=True, null=True, upload_to='recordings/audio/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('recording_started', models.DateTimeField(auto_now_add=True)),
                ('recording_finished', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='core.livestream')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'db_table': 'recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recordings_count', models.PositiveIntegerField(default=0)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_task', to='core.youtubechannel')),
            ],
            options={
                'verbose_name': 'Monitoring Task',
                'verbose_name_plural': 'Monitoring Tasks',
                'db_table': 'monitoring_tasks',
            },
        ),
        migrations.AddField(
            model_name='livestream',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='core.youtubechannel'),
        ),
    ]
