# Generated by Django 4.2.7 on 2025-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
