# Generated by Django 4.2.7 on 2025-11-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_youtubechannel_video_count_youtubechannel_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='is_active',
        ),
    ]
