# Generated by Django 5.1.2 on 2024-11-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='dropdown_field',
            field=models.CharField(choices=[('option1', 'Раз в 15 минут'), ('option2', 'Раз в 30 минут'), ('option3', 'Раз в 1 час'), ('option4', 'Раз в 2 часа')], max_length=10),
        ),
    ]
