# Generated by Django 5.1.2 on 2024-12-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='dropdown_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='text_field',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='interval',
            field=models.IntegerField(choices=[(1, '1 минута'), (5, '5 минут'), (10, '10 минут'), (30, '30 минут'), (60, '1 час')], default=1),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
