# Generated by Django 5.1.2 on 2024-12-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mymodel_interval_alter_mymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
    ]
