# Generated by Django 4.2.7 on 2025-08-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('handle', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('channel_created_date', models.DateField(blank=True, null=True)),
                ('subscribers_count', models.IntegerField(default=0)),
                ('current_streams_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('record_count', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.channel')),
            ],
        ),
        migrations.CreateModel(
            name='StreamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stream_url', models.URLField(default='')),
                ('started_at', models.DateTimeField()),
                ('duration_sec', models.IntegerField(default=0)),
                ('ts_relpath', models.CharField(blank=True, max_length=200)),
                ('mp3_relpath', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.channel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['handle'], name='tracker_cha_handle_ddb2e7_idx'),
        ),
    ]
