# Generated by Django 5.2.5 on 2025-08-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Имя канала на YouTube', max_length=255)),
                ('handle', models.CharField(help_text='Псевдоним (handle) без @', max_length=30, unique=True)),
                ('url', models.URLField(help_text='Ссылка на канал')),
                ('country', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('subscribers', models.PositiveIntegerField(blank=True, null=True)),
                ('live_count', models.PositiveIntegerField(default=0)),
                ('has_task', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tracker.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('ts_relpath', models.CharField(blank=True, max_length=500)),
                ('mp3_relpath', models.CharField(blank=True, max_length=500)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tracker.channel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tracker.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
