# Generated by Django 4.2.7 on 2025-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_channel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
